version: '3'
services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:1.30.5-alpine
    volumes: 
      - ${VW_DB_PATH}:/data/
    ports:
      - ${VW_PORT}:80
